# Generated by Django 2.2.6 on 2019-11-14 23:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20191110_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
